### ISSUE TITLE
Proposal: release testing-utils as an artifact to Maven Central Repository

### ISSUE THREAD

**Issue by pwittchen** [JakeWharton/RxBinding#149]
Hi,

Thanks for another great open-source project.

I think, it may be useful if `testing-utils` will be released to Maven Central Repository as a separate artifact. In one of my projects I'm using `RecordingObserver` class from RxBinding project (former NotRxAndroid) to test Observables from RxJava in my unit tests. Now, I have to copy `RecordingObserver` manually to my project and then I can use it. It will be nice if I could simply add appropriate `androidTestCompile` dependency and then use the newest version of this class as well as other testing utils.

Name of dependency can be as follows:

```
com.jakewharton.rxbinding:rxbinding-testing-utils:0.0.1
```

Regards,
Piotr

**Comment by dlew** [comment]
FYI, there's `TestSubscriber` in RxJava that works fairly well for my testing purposes.

**Comment by pwittchen** [comment]
@dlew Thanks for the information. I didn't know `TestSubscriber` and I'll take a look on that.

**Comment by JakeWharton** [comment]
I'm personally not a fan of TestSubscriber or TestScheduler in RxJava. I use variations of RecordingObserver all over. Sometimes blocking, sometimes non-blocking. At this point I think it's useful but it's not setup to be completely re-usable. If it ever does, I'd put it in a separate project rather than embedded here.
