### ISSUE TITLE
New release for Kotlin

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxBinding#175]
Currently, the release for Kotlin is built on M12 while Kotlin is now at 1.0 Beta candidate and the current version of Kotlin does not handle M12 generated binaries.

However the recent change to 23.1.0 for support library broke our builds since I'm not sure 23.1.0 is available from Maven so we actually had to select a specific snapshot version before that.

**Comment by JakeWharton** [comment]
The next snapshot will work with 1.0 the beta.

**Comment by dalewking** [comment]
Sorry, I wasn't clear. The issue was not that you needed to go to 1.0 Beta. The incompatibility was already there between M14 and M12. My complaint was that there needs to be a RELEASE with support for the newer binaries and not require using a snapshot in order to build.

Snapshots are dangerous as we found out when our build broke because of the switch to 23.1.0 of support library.

**Comment by JakeWharton** [comment]
There will be a release when there's a release. As with all my projects, no ETAs are given. I'm especially not going to rush something because of this, and as you said, the incompatibility was already there anyway.

If you don't want the volatility of snapshots, the aars can be copied into the project or versions can be deployed to places like an internal Artifactory or Nexus.

**Comment by dalewking** [comment]
The point is though what you have already released has been "broken" for weeks now since the release of M14 of Kotlin. Even if you made a hotfix of what's already been released to move it to the latest Kotlin that would be extremely helpful.

**Comment by JakeWharton** [comment]
I'm working on 0.3.0 this week. I don't want to redirect any of that effort. In the future I'll try to make releases more frequent to eliminate the staleness problem.
