### ISSUE TITLE
how to solve the subscriber in  RxView.clicks(View) while I get the Error 

### ISSUE THREAD

**Issue by MiJack** [JakeWharton/RxBinding#212]
Hi guy,thank you for the RxBinding Library . I feel it's wonderful to use it while developing android application . However , I  has the confusion that how to solve the subscriber in  RxView.clicks(View) while I get the Error . Code below is a case :

```
RxView.clicks(button)
   .subscriber(
       new Subscriber<Void>(){
          void onNext(Void aVoid){/* handle the normal operation*/}
          void onError(Error e){/* handle the error operation*/}
       }
   )
```

When error  happens , I will get A error message , but , after that , I won't get any message again.
So , it's a bug in RxBind or it isn't the best way to do it ?
What's the bast practice , could you show some demo code ,Thanks!

**Comment by JakeWharton** [comment]
Per the RxJava `Observable` contract, an error is a terminal even which shuts down the stream and makes it unusable for data moving forward. You have to create a new subscription or a whole new stream when an error occurs, but in this case you likely want to crash, since errors are very much like throwing an exception in Java.

Without a test case proving that RxBinding somehow is at fault here, I'm inclined to think this is just a lack of understanding about RxJava. Errors are exceptional cases and indicate some violent problem that should not be ignored. This is why RxJava tears down the stream when they occur.
