### ISSUE TITLE
Add support for formatting value as arg to resource string

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxBinding#224]
I often find that I have an observable value and the action is to format the value using a string resource and set a text view's text with the formatted text. I usually do a map to do the formatting and then subscribe with an RxTextView.text action. But wondering if it would be valuable to support this officially with a single action method in RxTextView as in:

	public static Action1<? super Object> textFormat(@NonNull final TextView view, @StringRes int format) {
		return new Action1<Object>() {
			@Override public void call(Object value) {
				view.setText(view.getContext().getString(format, value));
			}
		};
	}

I can see valid arguments against it (do you also do it for other text actions? What about if value is an array that represents multiple args?), but thought I should at least propose it for discussion.

Perhaps a better alternative is just a creator of a function for map to do formatting something like this:

    myObservable
        .map(RxContext.format(this, R.string.myFormat))
        .subscribe(RxTextView.text(myTextView));

**Comment by hzsweers** [comment]
I think this is out of the scope of this project. RxBinding is bindings for ui widgets/components, whereas this is more of something that would be appropriate for a sort of hypothetical "RxResources".

**Comment by JakeWharton** [comment]
Your arguments against it are also mine. I would like to see it experimented with in a standalone project since it has uses beyond just with RxBinding's text actions. Plus it lets the implementation evolve more rapidly to potentially correct those problems (and other unforeseen one).

If you do give it a shot, put a link here so I can look. Otherwise I don't think it belongs in the library since it's purely resource focused and has uses aside from just directly binding to one of the provided actions.
