### ISSUE TITLE
question: how do you integrate RxBinding with your architecture?

### ISSUE THREAD

**Issue by MidnightWonderer** [JakeWharton/RxBinding#235]
Hello there
I'm big fan of a lot of library you guys provided.

I looked into basic usage of RxBinding.
It look like this in my perception:
`Observable onEvent(View theView);`

The thing is I don't see how this fit in with other tools.
Also potentially overwhelm to maintain. (You guys do incredible job to keep it up to date.)

Let me explain in more concrete way:
Let says we use ButterKnife, RxBinding and Dagger2 in the project.
In order to get a view we call ButterKnife.Bind() on Activity creation
then we pass views into RxBinding to get observables.

Now how can we expose observables we got to the dependency graph of Dagger2?
Here naive method I can think of:
```
new EventModule(
 event1$,
 event2$,
 event3$,
);
```
This ugly and will not work in fragment because we build our component at activity level but we cannot create observable of fragment view outside of fragment (in activity).

I just found it much more cleaner just use Dagger2 to inject whatever Observer I need.
And use good old method:
```
setOnEventListener({
observer.onNext(value);
});
```
This way observables are still inside dependency graph lead to more decoupled module that also work across fragment.

But my intuition told me that there is something I don't know.
Even the tools I used are all involved by Jake himself. He still decided to create this library regardless of available pattern.
I just don't see the point of the library yet.
I guess I will understand once I see some benefit in concrete way.

I want to know how it has been used in conjunction with other library/framework/architecture.
Or what the issues you see in the old Rx approach.

Reply from someone in this project is great but reply from anyone is very welcome too.

**Comment by hzsweers** [comment]
I don't really follow your example. what is the type of these "events"? Where does `setOnEventListener()` come from?

There is *some* overlap between this and RxBinding, mainly around listeners (e.g. BK's `@OnClick` vs RxBinding's `RxView.clicks()`). I think one would argue that you should use whichever one suits your needs. If you want/need the composition that RxJava provides (say... a click starts a network request), then I'd use RxBinding. If you just need a simple binding to, say, launch a new activity or show a dialog, then maybe just stick with an annotated method. Beyond that though, I would say that BK and RxBinding are complementary.

I'd say that the beauty of this library is mainly around bridging non-reactive android APIs in an rx-friendly way. Anywhere you might have had callback or listener hell, you can instead replace them with RxBinding calls and maintain a consistent reactive architecture. This opens a lot of doors, anywhere from easy interop with other rx libraries to tying together the behaviors of multiple views/uis.

> Dagger

I'm not really sure where Dagger comes into all this, to me it's orthogonal. You definitely wouldn't really use dagger for any view components.

> what the issues you see in the old Rx approach.

What's the old Rx approach?

> I just don't see the point of the library yet.

I'll leave you with a common example: Say you have a `SearchView` that the user can perform searches in, and you want autocomplete suggestions from the server based on their input. You also want to delay until they've stopped typing for a long enough window so as not to spam the server, filter invalid inputs such as empty, and ignore the response if they started typing again since. Trying to do all that with BK alone would be hellish and full of stateful variables to keep track of everything. `RxTextView.changes()` gives you an easy entry point to that via single observable emitting next query texts.

**Comment by MidnightWonderer** [comment]
Hi @hzsweers thanks for the reply.
setOnEventListener is just plain old android way of event handling.
for instance view.setOnClickListener.
FYI I don't use (choose not to use) anotation binding of ButterKnife.

From my perspective callback and listener hell are already handled with RxJava alone without RxBinding.

The old school approach to bridge android implementation with RxJava is by using Rx Subject.

To see how Dagger kick in just imagine you have button on one fragment that affect another fragment.
Normally without Dagger you will implement some kind of bus with Subject to send some event from one to another and do the transformation of stream (event) within fragment that observe the event.

If Dagger is used Subject will be created inside Dagger dependency graph then cast to Observer and inject into fragment that send the event. This way no bus is needed to communicate between fragment further more the transformation of event is happened inside dependency graph and result Observable output will be inject to fragment that observe the event.
You will see that this way fragment itself will act as View (as in MV* architecture) without many business logic inside.

So RxJava & Dagger is currently forming my architecture because industry accepted Uncle Bob architecture is too purist for me and it concern something I might not even need.

For your example I believe that can be done with RxJava alone without RxBinding.
And if you use Dagger all you have to do in SearchView is Injecting Observer<String> for EditText and Observable<List<String>> for Spinner or what ever view you want to display.
The same thing cannot be done if you add RxBinding to the mix all business logic need to be reside inside your view. (From my current understanding.)

**Comment by JakeWharton** [comment]
RxBinding is just a more efficient way of mapping listeners to observables. You can do the same with subjects, but they're more expensive and dangerous types to work with.

Other than that, RxBinding doesn't play into architecture any differently.

**Comment by MidnightWonderer** [comment]
For anyone reading this issue in the future.
If you have open source app using RxBinding and you feel the code structure is quite good. (At least in your opinion.)
Please direct me to the repository.
I really want to have a look.

**Comment by egslava** [comment]
@MidnightWonderer now I think about that (imaginary) case :-) For instance, you have button, that sends user ticket to support system. Your program should send ticket for support system of user country. For instance, if I'm from Cyprus, ticket should be send to Cyprus support.

For that action we need to know user country and we get that information from server (server knows country because it knows user IP). So you should do two things:
1. Send request like getUserCountry.
2. Bind event like onClick.

So you can combineLatest() BehaviorSubject<Country> and submit.clicks() observables.

It's just imaginary case. But what do you think about it?
