### ISSUE TITLE
Action on multiple views

### ISSUE THREAD

**Issue by vladlichonos** [JakeWharton/RxBinding#236]
It is a suggestion/question to get feedback on idea of applying action onto multiple views instead of a single right now. Sometimes it is needed to disable/enable multiple views based on a property change (e.g. Observable<Boolean>). If we have 3-4 views to control it we would need to write setEnabled for each one, instead of listing what views to disable.

We could do something like this:
```java
@SafeVarargs
public static Action1<? super Boolean> allOf(Action1<? super Boolean>... actions) {
    return t -> {
        for (Action1<? super Boolean> action : actions) {
            action.call(t);
        }
    };
}
```

Then we have following:
```java
// before
viewModel.isLoading.subscribe(isLoading -> {
    email.setEnabled(!isLoading);
    password.setEnabled(!isLoading);
});

// after
viewModel.isLoading.map(isLoading -> !isLoading).subscribe(allOf(RxView.enabled(email), RxView.enabled(password)));
```

Any thoughts/feedback?

**Comment by JakeWharton** [comment]
I'll be very resistant adding it to RxBinding since it seems more appropriate as a generic thing for combining any RxJava `Action`s bounded by the same type. The advantages there are that you can optimize implementations for low counts and avoid the loop in the implementation as well as the array allocation for making the varargs method call. It also would allow you to combine multiple actions from unrelated views into a single stream (like two enabled's, a checked, and a selected, for example).

I would encourage you (or someone) to pursue this as a standalone project whose sole goal was the combination of the various `Action1` interfaces into helpers like `Action1s.combine(a, b, c)` or something.

**Comment by VladimirLichonos** [comment]
Created project here: https://github.com/VladimirLichonos/RxActions

**Comment by eleventigers** [comment]
@VladimirLichonos https://github.com/pakoito/RxActions :wink:

**Comment by VladimirLichonos** [comment]
@eleventigers yes, I already talked to author on Reddit. If you check code, these are very different libraries

**Comment by Zhuinden** [comment]
Well they are similar, but @VladimirLichonos 's library handles more cases. Mostly multi-parameter generic support seems to be the primary difference.
