### ISSUE TITLE
RxTextInputLayout-kotlin should accept CharSequence?

### ISSUE THREAD

**Issue by burntcookie90** [JakeWharton/RxBinding#297]
https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxTextInputLayout.kt#L28

Not using `CharSequence?` means the error cannot be unset via a `null` value, as per the [documentation](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html#setError(java.lang.CharSequence)).

**Comment by JakeWharton** [comment]
Yep. Not sure if the kotlin generation knows how to handle @Nullable from
the Java-side.

On Wed, Oct 19, 2016 at 9:07 PM Vishnu Rajeevan <notifications@github.com>
wrote:

https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxTextInputLayout.kt#L28

Not using CharSequence? means the error cannot be unset via a null value,
as per the documentation
<https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html#setError(java.lang.CharSequence)>
.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JakeWharton/RxBinding/issues/297>, or mute the thread

**Comment by burntcookie90** [comment]
Yeah, I was worried about that part.

**Comment by JakeWharton** [comment]
Shouldn't be too hard to add support for. I'm really busy for like two
weeks. If someone wants to tackle this it'd be great.

**Comment by burntcookie90** [comment]
I'll take a whack at it, I've got some free time

**Comment by burntcookie90** [comment]
Marking the type with `@Nullable` isn't supported in 7 :(

**Comment by JakeWharton** [comment]
Oh, right it's the parameterized type that needs marked not the enclosing
return type. Just put an annotation in 'internal' called
@ParameterTypeNullable that we can add to the method and use as an
indicator.

**Comment by JakeWharton** [comment]
er, @ParameterizedTypeNullable, that is

**Comment by JakeWharton** [comment]
Actually even that sounds like the enclosing type. How about
@GenericTypeNullable which is nice and plebeian instead of trying to be all
cute.

**Comment by burntcookie90** [comment]
Yep, that was gonna be my suggestion, I'll get it in tomorrow.
