### ISSUE TITLE
RxTextView returns a null editable initially

### ISSUE THREAD

**Issue by sreejithraman** [JakeWharton/RxBinding#369]
here's what my textview looks like:
````xml
<TextView
          android:id="@+id/textview"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:hint="example"
          android:maxLines="1"
          android:freezesText="true"
      />
````

this is what the call i am making looks like:
````java
 return RxTextView.afterTextChangeEvents(textview)
        .map(new Func1<TextViewAfterTextChangeEvent, Boolean>() {
          @Override
          public Boolean call(TextViewAfterTextChangeEvent changeEvent) {
              // changeEvent.editable() is null

          }
        });
````

**Comment by JakeWharton** [comment]
With what version?

**Comment by sreejithraman** [comment]
1.0.1

**Comment by OrdonTeam** [comment]
With current I suppose:
https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxTextViewTest.java#L164

**Comment by Joseph82** [comment]
I think this is due to the fact that the initial emitted value is obtained with `view.getEditableText()`, but a TextView shouldn't be editable by default, so it always returns null.

If you want to obtain a non null result (the text in the TextView) you should set `android:editable="true"`, even though this is deprecated.

**Comment by JakeWharton** [comment]
Yeah I don't have a good answer here beyond what @Joseph82 said. Since the event uses an `Editable` type there's not much we can do. I don't really want to write a custom `Editable` implementation just for the initial event should it return `null`.

I think a documentation change is probably all we can do.
