### ISSUE TITLE
Why doesn't click debounce?

### ISSUE THREAD

**Issue by vectrawr** [JakeWharton/RxBinding#401]
Butterknife has DebouncingOnClickListener, but I don't see an equivalent in this code. Are we expected to use the rx debounce operator?

**Comment by JakeWharton** [comment]
I added that to ButterKnife against my better judgment because there was no other hook. This library merely adapts clicks into a stream, though, and thus you can use whatever means you want in order to create a debounced behavior. So I don't know whether that's `debounce` or a custom click listener factory that uses a debouncing listener but it's now up to you instead of the library deciding for you.

**Comment by vectrawr** [comment]
there is a factory available? I don't see it. ViewClickObservable appears to always use it's own Listener class as the onclick listener.

**Comment by JakeWharton** [comment]
No you can make your own `Observable` that does the same thing as `RxView.clicks` but that uses a debouncing listener.
