### ISSUE TITLE
Emit timestamp for events instead of unspecified object

### ISSUE THREAD

**Issue by RobLewis** [JakeWharton/RxBinding#409]
For Observables that emit notifications of events like clicks, why not emit `System.currentTimeMillis()` instead of a content-free Object? Seems like this information could have value in some situations, and if it doesn't involve too much overhead, why not?

**Comment by JakeWharton** [comment]
That requires calls down into native code to get the `long` and then a call to `new Long(value)` to box it into an object for sending down the stream. Since 99% of people don't need this, we opt for an allocation-free approach of passing a marker instance.

Furthermore, the goal of the library is to map Android's listeners onto reactive streams and the Android listener for clicks doesn't pass a timestamp. So what if someone wants a timestamp for spinner selection events and timestamp? Now they have to manually do a thing to get a timestamp for the spinner (which otherwise passes an ID) whereas this hypothetical click listener provides it. And they also have to know about this behavior. In an effort to keep things simple, if you want this behavior or any other behavior that pulls a different value for the click you can use normal operators to compose it in via `.map { System.currentTimeMillis() }`.

Also this would be a breaking change and I'm not going to make a version 3.0 for such a small change.
