### ISSUE TITLE
Emit the view along with KeyEvents in View.keys observable

### ISSUE THREAD

**Issue by markotron** [JakeWharton/RxBinding#507]
Hello, 

I'm working on an app and need to listen for backspaces in the EditText. Once I receive a backspace I need to check the text in the view and do something. 

I can easily capture a reference to the view in my subscribe closure, but it would be nicer if the view was passed along with the KeyEvent in the observable. 

Does it make sense to create another observable `ViewKeyActionObservable` (or something like that) that will emit all the parameters of `OnKeyListener.onKey` function? 

Tnx.

**Comment by JakeWharton** [comment]
The principles of the library are such that we don't arbitrarily create new event types when ones already exist. Otherwise we would have to create a lot of additional overloads and we also would allocate wrapper objects in the case where most people didn't actually need them.

For this, your best bet is to call `map` and combine the view reference and the `KeyEvent` into a single object yourself. You can even encapsulate this into your own extension method.
```kotlin
fun View.keyEventsWithView() = keyEvents().map { it to this }
```
