### ISSUE TITLE
Need recyclerview with the state

### ISSUE THREAD

**Issue by SAGARSURI** [JakeWharton/RxBinding#524]
As per current implementation, we are not able to access the `Recyclerview` object in `scrollStateChanges` as you have provided for the `scrollEvents`.

https://github.com/JakeWharton/RxBinding/blob/9c474639cca93a3803b0f82a4596c0976896359c/rxbinding-recyclerview/src/main/java/com/jakewharton/rxbinding3/recyclerview/RecyclerViewScrollStateChangeObservable.kt#L46

**Comment by JakeWharton** [comment]
See https://github.com/JakeWharton/RxBinding/issues/507#issuecomment-476383897 for why we don't always create objects to pass the view.

The reason scrollEvents includes it is that we already always need to create an object to pass the dx and dy values, so it's basically free to include the recycler view. But in scroll state, we don't need a wrapper object to pass along the single state int. So instead of making everyone pay for creating an object when the overwhelming majority aren't going to need it, we instead move the burden onto you for creating the object only when you absolutely need both values.

**Comment by SAGARSURI** [comment]
Thank you so much for the clarification @JakeWharton
