### ISSUE TITLE
RxJava 3 support

### ISSUE THREAD

**Issue by BraisGabin** [JakeWharton/RxBinding#531]
It would be great to have support to RxJava3

**Comment by JakeWharton** [comment]
At the very least, I don't want to do any conversion until a 3.0 final is released. I do not want to maintain two versions.

**Comment by BraisGabin** [comment]
And what about a SNAPSHOT? To make it easier to test RxJava3 meanwhile the API is not freezed?

**Comment by JakeWharton** [comment]
A snapshot comes with the same problem because it still requires the source
to be maintained twice. For example, if we had done this and the ViewPager2
stuff landed last week how would it get migrated to 3? I'm not ready to
maintain two versions until 3.0 is much closer to release, and even then
I'm not excited about the prospect as the value proposition of 3.0 is
extremely low to the point where it feels like it's actually harming the Rx
ecosystem.

**Comment by hborders** [comment]
RxJava 3 has been released. :)

**Comment by DannyS86** [comment]
Any news here? 

The binding-library is great and we use excessively. During the migration to RxJava3 I figured out, that it does not support the RxJava3 dependencies, or am I wrong?

For example a call to the following still returns an `io.reactivex.Observable` instead of `io.reactivex.rxjava3.core.Observable`:
```
onReadingChangedObservable = RxTextView.textChanges(myEditText)
                .subscribeOn(io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.mainThread())
```
So it's not compatible with the rest of my RxJava3-code and stopped me from migration to RxJava3 for now...

**Comment by BraisGabin** [comment]
You can use https://github.com/akarnokd/RxJavaBridge meanwhile (if it's worth it the intermediate step)
