### ISSUE TITLE
RxTextView.textChanges exposes text behaviour instead of changes

### ISSUE THREAD

**Issue by konmik** [JakeWharton/RxBinding#61]
It uses `TextViewTextOnSubscribe` which emits first value without having a change.

**Comment by JakeWharton** [comment]
All property-based types emit the current value as documented. You can `.skip(1)` on these observables if you don't care about the initial value.

In the future I'll probably use an observable subclass with a `.skipInitialValue()` method for type-safe assurances around this behavior.

**Comment by konmik** [comment]
Where can I see the documentation you're referring to?

**Comment by JakeWharton** [comment]
The javadoc of the method.

**Comment by konmik** [comment]
OK, thanks. :)

**Comment by JakeWharton** [comment]
Also, as to the naming, see the README for the conventions for which the repo is currently following.

**Comment by konmik** [comment]
Why `clicks()` does not emit something on subscription but, but `textChanges()` emits? "Text change" is not a property, it is an event.

I have no experience with RxAndroid nor with RxBindings. This is just the first thing that I met here, and it does not look natural. I'm not arguing, just an opinion of a newcomer.

**Comment by JakeWharton** [comment]
A click occurs because of interaction and is not backed by a property on the view. A view's text property (along with others like visibility, being enabled, etc.) have values on which you are observing changes. The rule is that properties emit current values while actions (which have no value) only emit when they occur.

The distinction is only encoded in the documentation for each method, but I would like to formalize it a bit more in the future to make it clear.

**Comment by JakeWharton** [comment]
And I agree that perhaps we need to change naming rules because of this!

**Comment by PankajS24** [comment]
skipInitialValue is not working for me. Its still going inside
