### ISSUE TITLE
Why minSdkVersion 15?

### ISSUE THREAD

**Issue by asimaruk** [JakeWharton/RxBinding#96]
Is there any important reasons for 15 api version as minimum?
RxAndroid 0.24.0 worked well with 9 api level.

**Comment by plastiv** [comment]
See here how to make it work https://github.com/JakeWharton/RxBinding/issues/48

**Comment by JakeWharton** [comment]
Nothing beyond that there's really no reason to ship app updates to anyone on API levels lower than 15 anymore. It's already changed to 14 on `master` because I can't be bothered to argue against what seemed like someone reading an API distribution chart wrong. Do you have a compelling argument for API 9? (which is also a non-existent API like 14 and you probably mean 10)
